spring:
  profiles:
    active:
      - VN
      - dog
      - dev

db:
  username: YMLsuperUser
  password: YMLdbPassword
  jdbcUrl: YMLsomeUrlForDb


---
spring:
  config:
    activate:
      on-profile: prod
db:
  username: YMLProdsuperUser
  password: YMLProddbPassword
  jdbcUrl: YMLProdsomeUrlForDb

